### ISSUE TITLE
json: cannot unmarshal number into Go struct field postsDatesResponse.dates of type string

### ISSUE THREAD

**Issue by markphelps** [imwally/pinboard#2]
I'm encountering an error when trying to use the [PostDates](https://pkg.go.dev/github.com/benregn/pinboard#PostsDates) function.

```
json: cannot unmarshal number into Go struct field postsDatesResponse.dates of type string
```

It looks like the response from [https://api.pinboard.in/v1/posts/dates](https://pinboard.in/api/#posts_dates) for the `count` field is actually a JSON integer, not a string.

This causes the library to error when trying to unmarshal the JSON response into `postDatesResponse.dates` which is a `map[string]string`. It seems this type should instead be a `map[string]int`

When doing a curl request to the API with my token, I get the following:

```shell
curl 'https://api.pinboard.in/v1/posts/dates?auth_token=REDACTED&format=json' -H 'accept: application/json'
```

```json
{
  "user": "me",
  "tag": "",
  "dates": {
    "2021-08-28": 2,
    "2021-08-25": 1,
    "2021-08-05": 1,
    "2021-07-26": 1,
    "2021-07-08": 2,
    "2021-06-15": 1,
    "2021-05-30": 1,
    "2021-02-21": 1,
    "2020-10-12": 1,
    "2020-10-10": 2,
    "2020-10-02": 87
  }
}
```

**Comment by imwally** [comment]
Huh, well that's interesting...

```
=== RUN   TestPostsDates
    posts_test.go:229: json: cannot unmarshal number into Go struct field postsDatesResponse.dates of type string
```

I have to believe the API changed sometime in the last year or so (the last time I tested this) because even this package converts the response to an int: https://github.com/umahmood/pinboard/blob/668caef782f9a3754e2fa4b0a3c7f361bd573c20/pinboard.go#L409 

This one too: https://github.com/nwjsmith/thumbtack/blob/530fa0d6f12e511273a74a24e10b2683260670e1/lib/thumbtack/posts.rb#L254

Just wanted to make sure I'm not going crazy here.
